name: "web_scaffold"
mode: "dev"
port: 9090

log:
  level: "debug"
  filename: "./log/web_scaffold.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"       # mysql用户
  password: "******" # 用户登录密码
  dbname: "scaffold" # 建立的库
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: "******" # 密码，默认为""
  db: 0
  pool_size: 100